name: CI

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: The target `git` branch, `git` tag or `git` SHA to be released.
        required: true
      publish:
        description: Push the image to ghcr
        required: true
        type: boolean

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      with:
        ref: ${{ github.event.inputs.git-ref }}

    - name: Run Gosec Security Scanner
      uses: securego/gosec@1af1d5bb49259b62e45c505db397dd2ada5d74f8 # v2.14.0
      with:
        # G601 for zz_generated.deepcopy.go
        # G306 TODO: Expect WriteFile permissions to be 0600 or less
        # G307 TODO: Deferring unsafe method "Close"
        args: -exclude=G109,G601,G104,G204,G304,G306,G307 -tests=false -exclude-dir=test -exclude-dir=images/  -exclude-dir=docs/ ./...

  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      with:
        ref: ${{ github.event.inputs.git-ref }}

    - name: Set up Go
      id: go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: '1.20'
        check-latest: true

    - name: Run Lint
      run: ./hack/verify-golint.sh

    - name: Run go-fmt
      run: ./hack/verify-gofmt.sh

    - name: Run test
      run: make test

  release:
    if: ${{ github.event.inputs.publish }}
    name: Release
    runs-on: ubuntu-latest
    needs:
    - test-and-lint
    steps:
    - name: Check out ingress-nginx
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      with:
        ref: ${{ github.event.inputs.git-ref }}

    # Based on https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#publishing-a-package-using-an-action
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: blend
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push release image
      env:
        REGISTRY: ghcr.io/blend
        TAG: ${{ github.event.inputs.git-ref }}
        COMMIT_SHA: ${{ github.sha }}
        PLATFORMS: amd64
        BUILDX_PLATFORMS: linux/amd64
      run: |
        echo "creating release image..."
        make release
        docker push --all-tags "$REGISTRY/controller"
